{{- if .Values.gatewayOauth2Nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw.fullname" . }}-gateway-nginx
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-nginx
spec:
  type: ClusterIP
  ports:
    - port: 4181
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openclaw.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway-nginx
{{- end }}
